### ISSUE TITLE
Adding slides

### ISSUE THREAD

**Issue by KeHartmann** [code-shambles/jskongress2019#1]
[Angular, React, Vue and Co. – peacefully united thanks to Web Components and Micro Apps](https://www.softwarearchitekt.at/talk/jsKongress-munchen/micro-apps-angular) by Manfred Steyer

[Taming reactive node.js: Stream-oriented architecture with Nest](https://speakerdeck.com/kamilmysliwiec/taming-reactive-node-dot-js-stream-oriented-architecture-with-nest) by Kamil Myśliwiec

[Crafting solid state management: A principle based architecture](https://docs.google.com/presentation/d/1MzpYoK83gj3sVqhsH0LsEC1ADE8_D2fEk7GT78gqTTM/edit#slide=id.p) by Michael Hladky

**Comment by code-shambles** [comment]
> [Angular, React, Vue and Co. – peacefully united thanks to Web Components and Micro Apps](https://www.softwarearchitekt.at/talk/jsKongress-munchen/micro-apps-angular) by Manfred Steyer
> 
> [Taming reactive node.js: Stream-oriented architecture with Nest](https://speakerdeck.com/kamilmysliwiec/taming-reactive-node-dot-js-stream-oriented-architecture-with-nest) by Kamil Myśliwiec
> 
> [Crafting solid state management: A principle based architecture](https://docs.google.com/presentation/d/1MzpYoK83gj3sVqhsH0LsEC1ADE8_D2fEk7GT78gqTTM/edit#slide=id.p) by Michael Hladky

Thank you very much! I have just added these.
